// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `form:"name"`
	Password string `form:"password"`
}

type LoginReply struct {
	Token string `json:"token"`
}
